name: Dependabot - Build Python 3.10

env:
  TYPE: "recommended"
  DEV_APPLE_ID: ${{ secrets.DEV_APPLE_ID_MAOS }}
  DEV_TEAM_ID: ${{ secrets.DEV_TEAM_ID_MAOS }}
  DEV_APPLICATION_ID: ${{ vars.DEV_APPLICATION_ID  }}
  DEV_INSTALLER_ID: ${{ vars.DEV_INSTALLER_ID }}
  NOTARY_PASS: ${{ secrets.NOTARY_PASS }}
  PYTHON_VERSION: "3.10.9"

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: macos-12
    if: ${{ github.actor == 'dependabot[bot]' }}

    steps:
    - name: Checkout python repo
      uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
      with:
        fetch-depth: 0

    - name: Build as dependabot
      run: make dependabot
